(function(root,factory){
'use strict';
const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MZFinanceParser=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clean=v=>String(v??'').replace(/\r/g,'').replace(/\u00a0/g,' ').replace(/&nbsp;/gi,' ').replace(/\*\*/g,'').replace(/^\s*#{1,6}\s*/gm,'');
function money(v){const s=clean(v),neg=/^\s*-/.test(s),d=s.replace(/[^0-9]/g,'');return d?Number((neg?'-':'')+d):0;}
function find(text,labels){const raw=clean(text);for(const label of [].concat(labels)){const i=raw.toLowerCase().indexOf(label.toLowerCase());if(i<0)continue;const tail=raw.slice(i+label.length,i+label.length+100),m=tail.match(/([+-]?[0-9][0-9 .,'’]*)\s*USD/i);if(m)return money(m[1]);}return null;}
function cut(text,start,ends=[]){const raw=clean(text),low=raw.toLowerCase(),i=low.indexOf(start.toLowerCase());if(i<0)return'';let end=raw.length;for(const x of ends){const p=low.indexOf(x.toLowerCase(),i+start.length);if(p>=0)end=Math.min(end,p);}return raw.slice(i,end);}
function ratio(text,labels){const raw=clean(text);for(const label of [].concat(labels)){const i=raw.toLowerCase().indexOf(label.toLowerCase());if(i<0)continue;const tail=raw.slice(i+label.length,i+label.length+70),m=tail.match(/(\d+)\s*(?:\/\s*(\d+))?/);if(m)return{current:Number(m[1])||0,maximum:m[2]==null?null:Number(m[2])||0};}return null;}
function sum(o){return Object.values(o||{}).reduce((a,v)=>a+(v==null?0:Number(v)||0),0);}
function fingerprint(r){const s=[r.income.total,r.expenses.total,r.weeklyCosts.total,r.weeklyCosts.players,r.income.details.achievementReward,r.income.details.tickets,r.income.details.sponsors,r.matches.friendliesHome?.current,r.matches.friendliesHome?.maximum].join('|');let h=5381;for(let i=0;i<s.length;i++)h=((h<<5)+h)^s.charCodeAt(i);return'fin-'+(h>>>0).toString(36);}
function parseFinanceReport(text,capturedAt=Date.now()){
 const raw=clean(text),weeklyTitle=raw.includes('Cálculo de gastos semanales')?'Cálculo de gastos semanales':'Calculo de gastos semanales',inc=cut(raw,'Ingresos',['Gastos']),exp=cut(raw,'Gastos',['Cálculo de gastos semanales','Calculo de gastos semanales']),week=cut(raw,weeklyTitle,['Partidos generadores de ingresos']),matches=cut(raw,'Partidos generadores de ingresos');
 const incomeDetails={achievementReward:find(inc,'Recompensa de Logro'),facilities:find(inc,['Recaudación por instalaciones','Recaudacion por instalaciones']),tickets:find(inc,['Ingreso por venta de entradas','Ingresos por venta de entradas']),sponsors:find(inc,['Ingresos por espónsors','Ingresos por esponsors','Ingresos por sponsors']),playerSales:find(inc,['Venta de jugadores','Ingresos por venta de jugadores'])};
 const expenseDetails={stadiumConstruction:find(exp,['Construcción del estadio','Construccion del estadio']),playerPurchases:find(exp,'Compra de jugadores'),facilities:find(exp,'Gastos por instalaciones'),stadium:find(exp,'Gastos por el estadio'),playerSalaries:find(exp,'Sueldos de jugadores'),youth:find(exp,'Juveniles'),employees:find(exp,'Sueldos de empleados')};
 const weeklyCosts={players:find(week,'Sueldos de jugadores'),employees:find(week,'Sueldos de empleados'),stadium:find(week,'Gastos por el estadio'),facilities:find(week,'Gastos por instalaciones'),youth:find(week,'Juveniles'),total:find(week,'Total')};
 const report={capturedAt:Number(capturedAt)||Date.now(),income:{total:find(inc||raw,'Ingresos'),details:incomeDetails},expenses:{total:find(exp||raw,'Gastos'),details:expenseDetails},weeklyCosts,matches:{seniorLeagueHome:ratio(matches,'Partidos locales de Liga Senior'),youthLeagueHome:ratio(matches,'Partidos locales de Ligas Juveniles'),worldLeagueHome:ratio(matches,'Partidos en casa de la Liga Mundial'),friendliesHome:ratio(matches,'Partidos Amistosos de local'),officialCup:ratio(matches,'Partidos de Copa Oficial'),friendlyCupGroupHome:ratio(matches,'Partidos locales de fase de grupo de Copa Amistosa/Premiada'),friendlyCupPlayoffHome:ratio(matches,'Partidos locales de playoff de Copa Amistosa/Premiada'),friendlyLeagueHome:ratio(matches,'Partidos locales de Liga Amistosa'),scoutHome:ratio(matches,'Partidos Scout de local'),specialHome:ratio(matches,'Partidos Especiales de local'),federationClash:ratio(matches,'Desafíos de Clash de Federaciones')}};
 report.accountingResult=report.income.total!=null&&report.expenses.total!=null?report.income.total-report.expenses.total:null;report.fingerprint=fingerprint(report);
 const warnings=[];if(report.income.total==null)warnings.push('No se detectó el total de ingresos.');if(report.expenses.total==null)warnings.push('No se detectó el total de gastos.');if(weeklyCosts.total==null)warnings.push('No se detectó el total de gastos semanales.');
 const near=(a,b)=>Math.abs(a-b)<=Math.max(2,Math.round(Math.max(Math.abs(a),Math.abs(b))*.002)),a=sum(incomeDetails),b=sum(expenseDetails),c=sum({players:weeklyCosts.players,employees:weeklyCosts.employees,stadium:weeklyCosts.stadium,facilities:weeklyCosts.facilities,youth:weeklyCosts.youth});
 if(report.income.total!=null&&a&&!near(report.income.total,a))warnings.push('El detalle de ingresos no coincide con el total.');if(report.expenses.total!=null&&b&&!near(report.expenses.total,b))warnings.push('El detalle de gastos no coincide con el total.');if(weeklyCosts.total!=null&&c&&!near(weeklyCosts.total,c))warnings.push('El detalle de gastos semanales no coincide con el total.');
 const core=[report.income.total,report.expenses.total,weeklyCosts.total].filter(v=>v!=null).length;return{report,warnings,valid:core>=2,complete:core===3};
}
return{clean,money,find,ratio,fingerprint,parseFinanceReport};
});